version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  dashboard:
    build: .
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
